export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
        "deps",
        "ux",
      ],
    ],
    "header-max-length": [2, "always", 100],
    "scope-case": [2, "always", "lower-case"],
    "subject-case": [0],
    "body-leading-blank": [2, "always"],
    "footer-leading-blank": [2, "always"],
    "footer-max-line-length": [2, "always", 120],
  },
}
