title: "[Idea]: "
body:
  - type: markdown
    attributes:
      value: |
        ## 想法 | Idea
        与社区分享您的绝妙想法！
        Share your brilliant ideas with the community!

  - type: textarea
    id: description
    attributes:
      label: 想法描述 | Idea Description
      description: 您希望增加或改进什么？ | What do you want to add or improve?
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: 使用场景 | Use Case
      description: 这将如何解决问题？ | How would this solve a problem?
    validations:
      required: true

  - type: input
    id: ai-service
    attributes:
      label: 目标 AI 服务 | Target AI Service
      description: 这个想法与哪个 AI 服务相关？(e.g. ChatGPT, DeepSeek) | Which AI service is this related to?
      placeholder: 选填 | Optional
    validations:
      required: false

  - type: dropdown
    id: specific-platform
    attributes:
      label: 安装方式 | Installation Type
      options:
        - All Types
        - Browser Extension
        - Userscript
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 | Alternative Solutions
      description: 您是否考虑过其他方法？ | Have you considered other ways?
    validations:
      required: false
