title: "[Idea] "
body: |
  ## Idea Description / 想法描述
  <!-- Share your idea with the community! / 和社区分享您的想法！ -->

  ## Use Case / 使用场景
  <!-- How would this idea improve Ophel? / 这个想法将如何改进 Ophel？ -->

  ## Alternative Solutions / 替代方案
  <!-- Have you considered other ways? / 您是否考虑过其他方法？ -->
