title: "[Idea] "
body:
  - type: markdown
    attributes:
      value: |
        ## Idea / 想法
        Share your brilliant ideas with the community!
        与社区分享您的绝妙想法！

  - type: textarea
    id: description
    attributes:
      label: Idea Description / 想法描述
      description: What do you want to add or improve? / 您希望增加或改进什么？
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case / 使用场景
      description: How would this solve a problem? / 这将如何解决问题？
    validations:
      required: true

  - type: input
    id: ai-service
    attributes:
      label: Target AI Service / 目标 AI 服务
      description: Which AI service is this related to? (e.g. ChatGPT, DeepSeek) / 这个想法与哪个 AI 服务相关？
      placeholder: Optional / 选填
    validations:
      required: false

  - type: dropdown
    id: specific-platform
    attributes:
      label: Installation Type / 安装方式
      options:
        - All Types (所有方式)
        - Browser Extension (浏览器扩展)
        - Userscript (油猴脚本)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions / 替代方案
      description: Have you considered other ways? / 您是否考虑过其他方法？
    validations:
      required: false
