title: "[Showcase]: "
body:
  - type: markdown
    attributes:
      value: |
        ## 作品展示 | Showcase
        展示您使用 Ophel 制作的成果！
        Show off what you've built with Ophel!

  - type: textarea
    id: description
    attributes:
      label: 描述 | Description
      description: 您做了什么，或者您是如何使用 Ophel 的？ | What did you build or how are you using Ophel?
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: 链接 | Link
      description: 您的仓库、脚本或演示链接 | URL to your repo, script, or demo.
      placeholder: https://...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 截图 | Screenshots
      description: 请将图片拖拽至此以展示您的成果 | Drag and drop images here to show off your work.
    validations:
      required: false
