name: ✨ 功能需求 Feature Request
description: 提出新功能需求或改进建议 | Suggest an feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的建议！
        Thanks for your suggestion!

  - type: dropdown
    id: installation_type
    attributes:
      label: 适用环境 | Target Environment
      options:
        - All Environments (所有环境)
        - Browser Extension (浏览器扩展)
        - Userscript (油猴脚本)
    validations:
      required: true

  - type: dropdown
    id: ai_platform
    attributes:
      label: 适用 AI 平台 | Target AI Platform
      options:
        - All Platforms
        - Gemini
        - Gemini Enterprise
        - ChatGPT
        - Claude
        - Grok
        - AI Studio
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 功能简述 | Feature Summary
      description: 一句话描述该功能 | One sentence summary of the feature.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题背景 | Problem or Use Case
      description: 您希望解决什么问题？ | What problem are you trying to solve?
      placeholder: 我在使用...功能时，经常遇到...的问题 | I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 解决方案 | Proposed Solution
      description: 应该如何工作？ | How should it work?
      placeholder: 我希望能够... | I want to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案 | Alternatives Considered
      description: 是否考虑过其他方案？ | Any other ways you've considered?
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 其他信息 | Additional Context
      description: 设计图、截图或其他细节 | Mockups, screenshots, or extra details.
